import Papa from 'papaparse';
import type { Field, Project } from '../types';
import { parseCondition } from './conditions';

// ---------------------------------------------------------------------------
// Export the current form as a flat "enriched matrix" (one row per field/option)
// using the same column names the importer understands, so it round-trips and
// feeds the hybrid skill. Nested helpers (autoFillConcat, repeaters) are NOT
// representable here — those stay in the JSON / are generated by the skill.
// ---------------------------------------------------------------------------

export const MATRIX_HEADERS = [
  'Pasos Formulario',
  'Sección',
  'Nombre del campo en formulario',
  'Tipo de dato',
  'Valor',
  'Regla',
  'Obligatorio',
  'Visualización en Formularios',
  'Nombre del campo en el JSON',
  'Nombre del campo en el PDF',
  'id',
] as const;

function visualization(f: Field): string {
  if (f.hidden) return 'No Aplica';
  if (f.readOnly) return 'Disabled / Visible';
  return 'editable / input del usuario / visible';
}

/** Human-readable rendering of a serialized condition (for the "Regla" column). */
function ruleText(f: Field): string {
  const g = parseCondition(f.conditionalVisibility);
  if (!g || g.conditions.length === 0) return '';
  const parts = g.conditions.map((c) => {
    if (c.operator === 'equals') return `${c.fieldId} = ${c.value ?? ''}`;
    if (c.operator === 'empty') return `${c.fieldId} vacío`;
    return `${c.fieldId} con valor`;
  });
  return `Se muestra si ${parts.join(g.logic === 'or' ? ' o ' : ' y ')}`;
}

export function formToMatrixRows(project: Project): Record<string, string>[] {
  const rows: Record<string, string>[] = [];
  const sourceNameOf = (f: Field) => {
    const sm = f.sourceMeta as Record<string, unknown> | null;
    return typeof sm?.sourceName === 'string' ? (sm.sourceName as string) : '';
  };
  for (const section of project.form.sections) {
    for (const sub of section.subsections) {
      for (const f of sub.fields) {
        rows.push({
          'Pasos Formulario': section.title,
          'Sección': sub.title,
          'Nombre del campo en formulario': f.radioGroupLabel ?? f.label,
          'Tipo de dato': f.type,
          'Valor': f.radioGroupLabel ? String(f.jsonValue ?? f.label ?? '') : '',
          'Regla': ruleText(f),
          'Obligatorio': f.required ? 'Si' : '',
          'Visualización en Formularios': visualization(f),
          'Nombre del campo en el JSON': f.salidaJSON ?? '',
          'Nombre del campo en el PDF': sourceNameOf(f),
          id: f.id,
        });
      }
    }
  }
  return rows;
}

export function matrixToCsv(project: Project): string {
  return Papa.unparse({ fields: [...MATRIX_HEADERS], data: formToMatrixRows(project).map((r) => MATRIX_HEADERS.map((h) => r[h] ?? '')) });
}

export function downloadCsv(text: string, filename: string): void {
  const blob = new Blob(['﻿' + text], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export async function downloadMatrixXlsx(project: Project, filename: string): Promise<void> {
  const XLSX = await import('xlsx');
  const rows = formToMatrixRows(project);
  const aoa = [[...MATRIX_HEADERS], ...rows.map((r) => MATRIX_HEADERS.map((h) => r[h] ?? ''))];
  const ws = XLSX.utils.aoa_to_sheet(aoa);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Ficha');
  const out = XLSX.write(wb, { type: 'array', bookType: 'xlsx' }) as ArrayBuffer;
  const blob = new Blob([out], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
